### ISSUE TITLE
Not display new image if I change .image property of a node

### ISSUE THREAD

**Issue by Nvt2106** [AlexSuleap/angular-tree-widget#1]
$scope.$on('selection-changed', function (e, node) {
        // node - selected node in tree
        $scope.selectedNode = node;
        $scope.selectedNode.image = "url to new image";
    });

However, icon is disappeared rather than displaying new image.

**Comment by AlexSuleap** [comment]
Hi Tuan,

Thanks for letting me know. The problem is linked to ng-style which is not updated correctly if I use [{{}}](AngularJS - ng-style does not update css background property).

I will create a new version today with a fix.

**Comment by AlexSuleap** [comment]
I have uploaded a new version v1.0.1 with a fix to this issue.

**Comment by Nvt2106** [comment]
Thanks AlexSuleap!
