### ISSUE TITLE
Question: Project in Bower?

### ISSUE THREAD

**Issue by ajmarmar** [AlexSuleap/angular-tree-widget#2]
Hi,

I like the your project and I want to use in my project, but is it possible that you upload the project in bower?

Regards.

**Comment by AlexSuleap** [comment]
I will try to do it over the week-end.

**Comment by miguelchico** [comment]
Hi @AlexSuleap,

I'm really interested in this feature and I can build it for you if you agree.

**Comment by miguelchico** [comment]
I created a pull request for you if you're interested.
https://github.com/AlexSuleap/angular-tree-widget/pull/5
