### ISSUE TITLE
How can I use a search to limit the model set of nodes displayed

### ISSUE THREAD

**Issue by BobFleischman** [AlexSuleap/angular-tree-widget#3]
I tried <tree nodes='treeNodes | filter:query' options='options'></tree> but got a strange response, rather than the list getting smaller, it got larger.

I also tried adding the filter inside your js file at the ng-repeat. No Joy.

Any Ideas?

**Comment by AlexSuleap** [comment]
Up to now the tree does not support search, to control the nodes visibility you have to add/remove nodes from the model. I will try to add a hidden property on node level to make it a little easier; and for the future to implement a real search.

**Comment by BobFleischman** [comment]
Thank you. Please let me know if there is anything that you would like me to test.

**Comment by miguelchico** [comment]
Hi!

I created a [pull request](https://github.com/AlexSuleap/angular-tree-widget/pull/8) adding a basic search mechanism.
