### ISSUE TITLE
Tree binding taking long time

### ISSUE THREAD

**Issue by Sivanthikani** [AlexSuleap/angular-tree-widget#4]
I would like to use this tree binding in my project. But when i check with long tree nodes lets say 2000, tree binding taking long time. Is there anything am missing.

**Comment by AlexSuleap** [comment]
For 2000 nodes the three should not have any problems.

How do you create your tree?

If you create the tree by pushing each node into the tree scope is going to be slow;  Why: for each node I have to redraw the tree.
Ex: Slow

$scope.tree=[];
$scope.tree.push(node1);
.........
$scope.tree.push(node2000);

If you want better performances, use a local variable:

var tree=[];
tree.push(node1);
.........
tree.push(node2000);

$scope.tree=tree;

This way you will draw the tree only once.
