### ISSUE TITLE
Register component in bower

### ISSUE THREAD

**Issue by miguelchico** [AlexSuleap/angular-tree-widget#9]
Hi @AlexSuleap,

Have you register the component in bower repository?

I still can't find it.

If you need any assistance, just ask me.

Thanks!

**Comment by AlexSuleap** [comment]
Done! bower search angular-tree-widget

**Comment by miguelchico** [comment]
Thank you Alex.

Could you create a tag with the latest changes to make them available?

**Comment by AlexSuleap** [comment]
Done; Thanks for the support.

**Comment by miguelchico** [comment]
My pleasure.
